<?php
 goto X6TpZ; arnW3: include "\164\145\x6d\160\154\141\x74\x65\x73\x2f\164\x6f\160\x4e\141\x76\x62\141\x72\56\160\x68\160"; goto kt2Bv; kt2Bv: ?>
<div class="right_col"role="main"><div class=""><div class="page-title"><div class="title_left"><h3>Barriles</h3></div></div><div class="clearfix"></div><div class="row"><div class="col-md-12 col-sm-12"><div class="x_panel"><div class="x_title"><h2>Conteo de barriles</h2><div class="clearfix"></div></div><form><div class="col-md-12 well"style="overflow:auto"><div class="col-sm-4"></div><fieldset class="col-md-4"><div class="control-group"><div class="controls"><div class="col-md-12 form-group has-feedback row xdisplay_inputx"><input aria-describedby="inputSuccess2Status"class="form-control has-feedback-left"id="single_cal1"placeholder=""> <i aria-hidden="true"class="fa fa-calendar form-control-feedback left"style="color:#000"></i> <span class="sr-only"id="inputSuccess2Status">(success)</span></div></div></div></fieldset><div></div><div class="col-sm-4 col-sm-4"><button class="btn btn-success"id="buscar_barriles">Buscar</button></div></div></form><div class="x_content"><div class="x_content"><div style="text-align:center"><div class="botones-container"><button class="btn boton-margen boton-responsivo btn-primary text-light"onclick='$("#table_barriles").DataTable().button(".buttons-copy").trigger("click")'>Copiar al portapapeles</button> <button class="btn boton-margen boton-responsivo btn-primary text-light"onclick='$("#table_barriles").DataTable().button(".buttons-excel").trigger("click")'>Generar excel</button> <button class="btn boton-margen boton-responsivo btn-primary text-light"onclick='$("#table_barriles").DataTable().button(".buttons-pdf").trigger("click")'>Generar PDF</button> <button class="btn boton-margen boton-responsivo btn-primary text-light"onclick='$("#table_barriles").DataTable().button(".buttons-print").trigger("click")'>Imprimir documento</button></div><table class=".progress table table-bordered table-striped"id="table_barriles"style="width:100%"><thead><tr><th>Vacios</th><th>Surtidos</th><th>Balance</th><th>Turno</th></tr></thead><tbody></tbody></table></div></div></div></div></div></div></div></div><footer><div class="pull-right">APTIV - Materials Admin Tool</div><div class="pull-left">Desarrollado por: Ing Joel Andrade Enriquez</div><div class="clearfix"></div></footer></div></div><?php  goto AXZ2f; ran0G: ?>
</div></div><?php  goto arnW3; Fe8E2: ?>
<title>APTIV - BARRILES</title><style type="text/css">.left_col{background:#415f7c!important}</style><body class="nav-md"><div class="body container"><div class="main_container"><div class="left_col col-md-3"><div class="left_col scroll-view"><?php  goto rofhQ; AXZ2f: include "\x74\x65\155\x70\154\141\x74\x65\163\57\x66\157\157\164\x65\162\x4c\151\x62\163\x2e\x70\150\160"; goto gvUUP; HgSzM: include "\x74\x65\155\160\x6c\x61\x74\x65\x73\57\x6e\x61\166\x62\x61\162\x2e\x70\x68\160"; goto ran0G; rofhQ: include "\164\x65\x6d\160\154\141\164\145\x73\57\154\157\147\157\56\x70\150\x70"; goto oNHmr; X6TpZ: ?>
<!doctypehtml><html lang="es"><?php  goto G16JC; G16JC: include "\x74\x65\x6d\x70\154\x61\x74\145\163\x2f\x68\x65\x61\144\x65\x72\x2e\160\150\x70"; goto Fe8E2; oNHmr: ?>
<div class="clearfix"></div><br><?php  goto HgSzM; gvUUP: ?>
</body></html><script src="build/js/getIP_origin.js"></script><script src="build/js/data_barriles_origin.js"></script><style type="text/css">.dtr-title{color:#000!important}.dtr-data{color:#000!important}#table_barriles_info{text-align:left!important}#table_barriles_length{text-align:left!important}.boton-margen{margin-right:10px!important}@media (max-width:767px){.botones-container{display:flex;flex-wrap:wrap;justify-content:center}}@media (max-width:480px){.botones-container{flex-direction:column}}.x_title span{color:#fff}</style>
<script type="text/javascript">
  window.location.replace('conversiones.php');
</script>